// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzjteuvXwizOSbuIURn0Wz5rsOrO6a01E',
    appId: '1:826985992317:web:ef1428696f283f2a22e114',
    messagingSenderId: '826985992317',
    projectId: 'qlda-50910',
    authDomain: 'qlda-50910.firebaseapp.com',
    storageBucket: 'qlda-50910.firebasestorage.app',
    measurementId: 'G-QS953YDV8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1bJmasgd_54YfyxS9qTvsPJ2SO5ElBI',
    appId: '1:826985992317:android:8b528c891c819bba22e114',
    messagingSenderId: '826985992317',
    projectId: 'qlda-50910',
    storageBucket: 'qlda-50910.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQchoNR45-jbjNMr7yXtSqpE_p0VTHrR4',
    appId: '1:826985992317:ios:c89196d10bcd0e4822e114',
    messagingSenderId: '826985992317',
    projectId: 'qlda-50910',
    storageBucket: 'qlda-50910.firebasestorage.app',
    iosBundleId: 'com.example.banking',
  );
}
